import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from './components/sidebar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: " | dbServer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isLoggedIn = true;

  return (
    <html lang="nb">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          {isLoggedIn && (
          <Sidebar />
          )}
          <section className="flex flex-col bg-slate-50 items-center justify-center w-full">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}